{{- if .Values.rhai.scriptFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "router.rhaiConfigMapName" . }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
data:
  main.rhai: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.rhai.scriptFile "context" $ ) | nindent 4 }}
{{- end }}
